import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { BarChart, Bar, ResponsiveContainer, CartesianGrid, XAxis, YAxis, Tooltip } from 'recharts';
import api from '../../api/client';
export const money = value => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value||0);
export function DividendRows({ payments, onEdit, onDelete }) {
  if(!payments.length)return <div className="empty-mini">No dividend payments yet. Add a received payment to start tracking income.</div>;
  return <div className="dividend-table-wrap"><table className="dividend-table"><thead><tr>{['Payment Date','Symbol','Provider','Amount','Payment','Frequency',...(onEdit?['Actions']:[])].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{payments.map(p=><tr key={p._id}><td>{new Date(p.paymentDate).toLocaleDateString('en-US',{timeZone:'UTC'})}</td><td><strong>{p.symbol}</strong></td><td>{p.provider}</td><td className="positive"><strong>{money(p.amount)}</strong></td><td><span className="dividend-badge">{p.paymentType}</span></td><td>{p.frequency}</td>{onEdit&&<td><div className="row-actions"><button className="btn btn-sm btn-outline-primary" aria-label={`Edit ${p.symbol} dividend`} onClick={()=>onEdit(p)}>Edit</button><button className="btn btn-sm btn-outline-danger" aria-label={`Delete ${p.symbol} dividend`} onClick={()=>onDelete(p)}>Delete</button></div></td>}</tr>)}</tbody></table></div>;
}
export default function DividendSummary({ selectedDate, showRecent=false }) {
  const [data,setData]=useState(null),[error,setError]=useState(''),[period,setPeriod]=useState('monthly');
  const load=useCallback(()=>api.get('/dividends/summary',{params:{date:selectedDate}}).then(r=>{setData(r.data.data);setError('');}).catch(e=>setError(e.message)),[selectedDate]);
  useEffect(()=>{load();window.addEventListener('dividends-changed',load);return()=>window.removeEventListener('dividends-changed',load);},[load]);
  const year=selectedDate.slice(0,4),month=new Date(`${selectedDate}T12:00:00Z`).toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'}),quarter=Math.floor((Number(selectedDate.slice(5,7))-1)/3)+1;
  return <section className="card-panel dividend-panel"><div className="card-title"><div><h2>Dividend Income</h2><p className="dividend-caption">Received payments · Daily goals continue to measure trading profit</p></div><div className="tabs" aria-label="Dividend chart period">{['monthly','quarterly','yearly'].map(p=><button key={p} className={period===p?'active':''} aria-pressed={period===p} onClick={()=>setPeriod(p)}>{p[0].toUpperCase()+p.slice(1)}</button>)}</div></div>
    {error?<div className="alert alert-danger" role="alert">{error}</div>:!data?<div className="loading">Loading dividend income…</div>:<><div className="dividend-overview"><div><div className="dividend-metrics">{[['Month',data.month,month],['Quarter',data.quarter,`Q${quarter} · ${year}`],['Year',data.year,year]].map(([label,value,sub])=><div key={label}><small>{label.toUpperCase()}</small><strong className="positive">{money(value)}</strong><span>{sub}</span></div>)}</div><p className="dividend-caption">All-time: {money(data.total)} · Cash {money(data.cash)} · Reinvested {money(data.reinvested)}</p><small className="text-muted">Totals use payment dates. Reinvested dividends count once as income.</small></div><div><p className="dividend-caption">{period==='yearly'?'Income by year':`Income by ${period==='monthly'?'month':'quarter'} · ${year}`}</p><div className="dividend-chart"><ResponsiveContainer><BarChart data={data[period]}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label"/><YAxis tickFormatter={v=>`$${v}`}/><Tooltip formatter={v=>[money(v),'Dividends']}/><Bar dataKey="amount" fill="#6457e6" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></div></div>{showRecent&&<div className="dividend-recent"><div className="card-title"><h2>Recent Dividend Payments</h2><Link to="/dividends">View All Dividends →</Link></div><DividendRows payments={data.recentPayments}/></div>}</>}
  </section>;
}
