import { useCallback, useEffect, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import api from '../api/client';
import DividendModal, { today } from '../components/dividends/DividendModal';
import DividendSummary, { DividendRows, money } from '../components/dividends/DividendSummary';
export default function Dividends(){
  const {openAddDividend}=useOutletContext();
  const [payments,setPayments]=useState([]),[filters,setFilters]=useState({symbol:'',provider:'',from:'',to:''}),[applied,setApplied]=useState({}),[editing,setEditing]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[deleting,setDeleting]=useState(false);
  const load=useCallback(()=>{setLoading(true);return api.get('/dividends',{params:applied}).then(r=>{setPayments(r.data.data);setError('');}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[applied]);
  useEffect(()=>{load();window.addEventListener('dividends-changed',load);return()=>window.removeEventListener('dividends-changed',load);},[load]);
  async function remove(payment){if(deleting||!window.confirm(`Delete ${money(payment.amount)} dividend from ${payment.symbol}? Total profit will be recalculated.`))return;setDeleting(true);try{await api.delete(`/dividends/${payment._id}`);window.dispatchEvent(new Event('dividends-changed'));}catch(e){setError(e.message);}finally{setDeleting(false);}}
  return <><div className="page-heading"><div><h1>Dividends</h1><p>Track received payments and monthly, quarterly, and annual income</p></div><button className="btn btn-primary" onClick={openAddDividend}>+ Add Dividend</button></div><DividendSummary selectedDate={today()}/><section className="card-panel dividend-panel"><div className="card-title"><h2>Dividend Payments</h2><span className="dividend-caption">{payments.length} payments · {money(payments.reduce((n,p)=>n+p.amount,0))} in results</span></div><form className="dividend-filters" onSubmit={e=>{e.preventDefault();setApplied({...filters});}}>{[['symbol','Symbol','text'],['provider','Provider / Account','text'],['from','From','date'],['to','To','date']].map(([key,label,type])=><label key={key}>{label}<input className="form-control" type={type} value={filters[key]} onChange={e=>setFilters(f=>({...f,[key]:e.target.value}))}/></label>)}<button className="btn btn-primary" type="submit">Filter</button><button className="btn btn-outline-secondary" type="button" onClick={()=>{setFilters({symbol:'',provider:'',from:'',to:''});setApplied({});}}>Reset</button></form>{error&&<div className="alert alert-danger" role="alert">{error}</div>}{loading?<div className="loading">Loading payments…</div>:<DividendRows payments={payments} onEdit={setEditing} onDelete={remove}/>}</section><DividendModal isOpen={!!editing} payment={editing} toggle={()=>setEditing(null)} onSaved={()=>setEditing(null)}/></>;
}
