import{useEffect,useState}from'react';import{ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid}from'recharts';import api from'../api/client';
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v||0),today=()=>new Date().toISOString().slice(0,10);
export default function Reports(){
 const[filters,setFilters]=useState({from:`${today().slice(0,8)}01`,to:today(),provider:'',symbol:''}),[data,setData]=useState(null),[error,setError]=useState('');
 const load=()=>api.get('/reports/profit',{params:filters}).then(r=>setData(r.data.data)).catch(e=>setError(e.message));
 useEffect(()=>{load()},[]);
 function submit(e){e.preventDefault();load()}
 return<><div className={'page-heading'}><div><h1>Reports</h1><p>Filter and compare your realized trading performance</p></div></div><form className={'card-panel report-filters'} onSubmit={submit}><label>From<input type={'date'} value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>To<input type={'date'} value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><label>Provider<input placeholder={'All providers'} value={filters.provider} onChange={e=>setFilters({...filters,provider:e.target.value})}/></label><label>Symbol<input placeholder={'All symbols'} value={filters.symbol} onChange={e=>setFilters({...filters,symbol:e.target.value.toUpperCase()})}/></label><button className={'btn btn-primary'}>Apply</button></form>{error&&<div className={'alert alert-danger'}>{error}</div>}{data&&<ReportContent data={data}/>}</>
}
function ReportContent({data}){const s=data.summary,cards=[['Total Profit',money(s.totalProfit)],['Total Trades',s.totalTrades],['Winning Trades',s.wins],['Losing Trades',s.losses],['Average / Trade',money(s.averageProfit)],['Largest Win',money(s.largestWin)],['Largest Loss',money(s.largestLoss)],['Win Rate',`${s.winRate.toFixed(1)}%`]];return<><div className={'analytics-grid'}>{cards.map(([a,b])=><article className={'card-panel metric-card'} key={a}><span>{a}</span><strong>{b}</strong></article>)}</div><div className={'phase-two-column'}><section className={'card-panel phase-chart'}><h2>Daily Profit</h2><ResponsiveContainer width={'100%'} height={280}><BarChart data={data.daily}><CartesianGrid strokeDasharray={'3 3'}/><XAxis dataKey={'date'}/><YAxis/><Tooltip formatter={money}/><Bar dataKey={'profit'} fill={'#6457e6'}/></BarChart></ResponsiveContainer></section><Ranking title={'Profit by Provider'} rows={data.providers}/></div><Ranking title={'Profit by Stock'} rows={data.symbols}/></>}
function Ranking({title,rows}){return<section className={'card-panel ranking'}><h2>{title}</h2>{rows.length?rows.map(row=><div key={row.name}><strong>{row.name}</strong><span>{row.trades} trades</span><b className={row.profit>=0?'positive':'negative'}>{money(row.profit)}</b></div>):<p className={'empty-mini'}>No closed trades in this period.</p>}</section>}
